export type kebunOption = {
    value: string;
    label: string;
  }

export const kebunOptions : kebunOption[] = [
    { value: "balai-benih-ks", label: "Balai Benih KS" },
    { value: "kbn-aba", label: "KBN ABA" },
    { value: "kbn-ado", label: "KBN ADO" },
    { value: "kbn-aja", label: "KBN AJA" },
    { value: "kbn-baj", label: "KBN BAJ" },
    { value: "kbn-bal", label: "KBN BAL" },
    { value: "kbn-bap", label: "KBN BAP" },
    { value: "kbn-ber", label: "KBN BER" },
    { value: "kbn-bul", label: "KBN BUL" },
    { value: "kbn-doi", label: "KBN DOI" },
    { value: "kbn-dos", label: "KBN DOS" },
    { value: "kbn-gub", label: "KBN GUB" },
    { value: "kbn-lar", label: "KBN LAR" },
    { value: "kbn-mar", label: "KBN MAR" },
    { value: "kbn-mat", label: "KBN MAT" },
    { value: "kbn-may", label: "KBN MAY" },
    { value: "kbn-mep", label: "KBN MEP" },
    { value: "kbn-osa", label: "KBN OSA" },
    { value: "kbn-pab", label: "KBN PAB" },
    { value: "kbn-paj", label: "KBN PAJ" },
    { value: "kbn-pam", label: "KBN PAM" },
    { value: "kbn-pdm", label: "KBN PDM" },
    { value: "kbn-plm", label: "KBN PLM" },
    { value: "kbn-pur", label: "KBN PUR" },
    { value: "kbn-sal", label: "KBN SAL" },
    { value: "kbn-sko", label: "KBN SKO" },
    { value: "kbn-teh", label: "KBN TEH" },
    { value: "kbn-tim", label: "KBN TIM" },
    { value: "kbn-tin", label: "KBN TIN" },
    { value: "kbn-tiu", label: "KBN TIU" },
    { value: "kbn-ton", label: "KBN TON" },
    { value: "kbn-ulu", label: "KBN ULU" },
    { value: "pks-aba", label: "PKS ABA" },
    { value: "pks-ado", label: "PKS ADO" },
    { value: "pks-aja", label: "PKS AJA" },
    { value: "pks-baj", label: "PKS BAJ" },
    { value: "pks-ber", label: "PKS BER" },
    { value: "pks-doi", label: "PKS DOI" },
    { value: "pks-dos", label: "PKS DOS" },
    { value: "pks-gub", label: "PKS GUB" },
    { value: "pks-may", label: "PKS MAY" },
    { value: "pks-osa", label: "PKS OSA" },
    { value: "pks-pab", label: "PKS PAB" },
    { value: "pks-pam", label: "PKS PAM" },
    { value: "pks-pur", label: "PKS PUR" },
    { value: "pks-sal", label: "PKS SAL" },
    { value: "pks-tim", label: "PKS TIM" },
    { value: "pks-tin", label: "PKS TIN" },
    { value: "pmt-doi", label: "PMT DOI" },
    { value: "pteh-but", label: "PTEH BUT" },
    { value: "pteh-tob", label: "PTEH TOB" }
];